---
- hosts: webservers
  user: root
  
  tasks:
   - name: Update Repository Debian
     apt: update_cache=yes
   - name: Install the package GIT for Debian
     apt:
       name: git
   - name: Install the package MariaDB for Debian
     apt:
       name: mariadb-server
   - name: Install the package APACHE
     apt:
       name: apache2
   - name: Install latest version of PHP5
     apt:
       name: php5
       state: present
       install_recommends: no
   - name: Install Module MySQL of PHP5
     apt:
       name: php5-mysql
       state: latest
       install_recommends: no
   - name: Install PHP module for Apache2
     apt: name=libapache2-mod-php5 state=present
   - name: Start Apache Service
     service:
       name: apache2
       state: restarted
       enabled: yes
   - name: Start MYSQL Service
     service:
       name: mysql
       state: started
       enabled: yes
   
   - shell: rm -rf /var/www/html/*
   - git:
       repo: 'https://github.com/demonkaen/pdemo_1.git'
       dest: /var/www/html/
       update: no
   - shell: chmod -R 755 /var/www/html/
   - shell: chown -R www-data:www-data /var/www/html/
   - shell: mysql -u root -h localhost </var/www/html/schema.sql
